"""Generate JSON test vectors from the validated reference implementation.

The Swift port in PulseLog/Sources/PulseLogSignal is verified against these,
stage by stage, so a transcription error in the DSP fails a unit test instead
of silently shipping wrong heart rates.
"""

import json
import numpy as np
import ppg_reference as ppg
import synthetic


def r(x, nd=9):
    if x is None:
        return None
    if isinstance(x, (list, tuple, np.ndarray)):
        return [round(float(v), nd) for v in x]
    return round(float(x), nd)


def main():
    out = {"_comment": "Generated by emit_vectors.py. Do not edit by hand.",
           "constants": {
               "minBPM": ppg.MIN_BPM, "maxBPM": ppg.MAX_BPM,
               "subharmonicPowerFloor": ppg.SUBHARMONIC_POWER_FLOOR,
               "confidenceThreshold": ppg.CONFIDENCE_THRESHOLD,
               "rrDispersionTolerance": ppg.RR_DISPERSION_TOLERANCE,
               "sparsePeriodSamples": ppg.SPARSE_PERIOD_SAMPLES}}

    # --- biquad coefficients -------------------------------------------------
    out["biquad"] = []
    for fs in (30.0, 24.0, 29.87):
        for kind, fn, fc in (("lowpass", ppg._butter2_lowpass_coeffs, 3.5),
                             ("highpass", ppg._butter2_highpass_coeffs, 0.7)):
            b0, b1, b2, a1, a2 = fn(fc, fs)
            out["biquad"].append({"kind": kind, "fs": fs, "cutoffHz": fc,
                                  "b0": r(b0), "b1": r(b1), "b2": r(b2),
                                  "a1": r(a1), "a2": r(a2)})

    # --- filtfilt on a deterministic input ------------------------------------
    t = np.arange(120) / 30.0
    probe = (np.sin(2 * np.pi * 1.2 * t) + 0.5 * np.sin(2 * np.pi * 0.15 * t)
             + 0.3 * np.sin(2 * np.pi * 6.0 * t))
    out["filtfilt"] = {
        "fs": 30.0, "input": r(probe),
        "bandpassed": r(ppg.bandpass(probe, 30.0)),
        "detrended": r(ppg.moving_average_detrend(probe, 30.0, 1.0)),
    }

    # --- autocorrelation ------------------------------------------------------
    sig = np.sin(2 * np.pi * 1.25 * t) + 0.4 * np.sin(2 * np.pi * 2.5 * t + 0.9)
    out["autocorrelation"] = {"input": r(sig), "acf": r(ppg.autocorrelation(sig))}

    # --- parabolic refinement -------------------------------------------------
    out["parabolic"] = []
    for vals, idx in (([0.1, 0.9, 0.4], 1), ([0.4, 0.9, 0.1], 1),
                      ([0.5, 0.8, 0.5], 1), ([0.2, 0.7, 0.69], 1)):
        out["parabolic"].append({"values": r(vals), "index": idx,
                                 "refined": r(ppg._parabolic_refine(np.array(vals), idx))})

    # --- RMSSD ----------------------------------------------------------------
    out["rmssd"] = []
    for peaks, fs in (([0, 30, 61, 89, 120, 150], 30.0),
                      ([0, 25, 50, 75, 100, 125, 150], 30.0),
                      ([0, 30, 65, 92, 130], 30.0)):
        out["rmssd"].append({"peaks": peaks, "fs": fs,
                             "rmssdMs": r(ppg.rmssd_ms(peaks, fs)),
                             "dispersion": r(ppg.rr_dispersion(peaks, fs))})

    # --- end-to-end pipeline --------------------------------------------------
    out["pipeline"] = []
    cases = [("nominal_72", 72, {}), ("nominal_55", 55, {}),
             ("fast_165", 165, {}), ("brady_46", 46, {}),
             ("weak_perfusion_88", 88, {"ac_dc_ratio": 0.0025}),
             ("wander_110", 110, {"breathing_amplitude_ratio": 8.0}),
             ("garbage_no_finger", 70, {"ac_dc_ratio": 0.00005,
                                        "sensor_noise_dc_ratio": 0.004}),
             ("high_rate_variable_195", 195, {"hrv_sd_ms": 60.0})]
    for name, bpm, kw in cases:
        ts, sig = synthetic.generate(bpm=bpm, seed=11, duration_s=20.0, **kw)
        res = ppg.analyze(ts, sig)
        out["pipeline"].append({
            "name": name, "trueBPM": bpm,
            "timestamps": r(ts), "values": r(sig),
            "expected": {"bpm": r(res["bpm"]), "confidence": r(res["confidence"]),
                         "fs": r(res["fs"]), "rmssdMs": r(res["rmssd_ms"]),
                         "isReportable": bool(res["is_reportable"]),
                         "beatCount": res["beat_count"],
                         "rrDispersion": r(res.get("rr_dispersion"))},
        })

    path = "../Tests/PulseLogSignalTests/Resources/ppg_vectors.json"
    import os
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(out, f, indent=1)
    size = os.path.getsize(path) / 1024
    print(f"wrote {path} ({size:.0f} KB)")
    for c in out["pipeline"]:
        e = c["expected"]
        print(f"  {c['name']:<22} true={c['trueBPM']:3d} est={e['bpm'] or 0:6.2f} "
              f"conf={e['confidence']:.2f} reportable={e['isReportable']}")


if __name__ == "__main__":
    main()
