import XCTest
@testable import PulseLogSignal

/// Verifies the Swift pipeline against vectors generated by the numerically
/// validated Python reference in `reference/`.
///
/// These tests exist because a transcription error in DSP code does not crash
/// or look wrong — it silently produces confident, specific, incorrect heart
/// rates. Checking each stage separately means a mistake fails at the stage
/// that caused it rather than surfacing as an unexplained end-to-end drift.
final class VectorTests: XCTestCase {

    // MARK: - Fixture loading

    struct Vectors: Decodable {
        struct Constants: Decodable {
            let minBPM, maxBPM, subharmonicPowerFloor, confidenceThreshold: Double
        }
        struct BiquadCase: Decodable {
            let kind: String, fs: Double, cutoffHz: Double
            let b0, b1, b2, a1, a2: Double
        }
        struct FiltfiltCase: Decodable {
            let fs: Double
            let input, bandpassed, detrended: [Double]
        }
        struct AutocorrelationCase: Decodable {
            let input, acf: [Double]
        }
        struct ParabolicCase: Decodable {
            let values: [Double], index: Int, refined: Double
        }
        struct RMSSDCase: Decodable {
            let peaks: [Int], fs: Double, rmssdMs: Double?
        }
        struct PipelineCase: Decodable {
            struct Expected: Decodable {
                let bpm: Double?, confidence: Double, fs: Double
                let rmssdMs: Double?, isReportable: Bool, beatCount: Int
            }
            let name: String, trueBPM: Double
            let timestamps, values: [Double]
            let expected: Expected
        }
        let constants: Constants
        let biquad: [BiquadCase]
        let filtfilt: FiltfiltCase
        let autocorrelation: AutocorrelationCase
        let parabolic: [ParabolicCase]
        let rmssd: [RMSSDCase]
        let pipeline: [PipelineCase]
    }

    static let vectors: Vectors = {
        guard let url = Bundle.module.url(forResource: "ppg_vectors", withExtension: "json"),
              let data = try? Data(contentsOf: url) else {
            fatalError("ppg_vectors.json missing — regenerate with reference/emit_vectors.py")
        }
        return try! JSONDecoder().decode(Vectors.self, from: data)
    }()

    private func assertClose(_ actual: [Double], _ expected: [Double],
                             tolerance: Double, _ label: String,
                             file: StaticString = #filePath, line: UInt = #line) {
        XCTAssertEqual(actual.count, expected.count, "\(label): length", file: file, line: line)
        guard actual.count == expected.count else { return }
        var worstIndex = 0
        var worst = 0.0
        for i in 0..<actual.count {
            let d = abs(actual[i] - expected[i])
            if d > worst { worst = d; worstIndex = i }
        }
        XCTAssertLessThan(worst, tolerance,
                          "\(label): worst deviation \(worst) at index \(worstIndex) "
                          + "(got \(actual[worstIndex]), expected \(expected[worstIndex]))",
                          file: file, line: line)
    }

    // MARK: - Constants

    func testConstantsMatchReference() {
        let c = Self.vectors.constants
        XCTAssertEqual(PPGConstants.minBPM, c.minBPM)
        XCTAssertEqual(PPGConstants.maxBPM, c.maxBPM)
        XCTAssertEqual(PPGConstants.subharmonicPowerFloor, c.subharmonicPowerFloor)
        XCTAssertEqual(PPGConstants.confidenceThreshold, c.confidenceThreshold)
    }

    // MARK: - Stages

    func testBiquadCoefficients() {
        for c in Self.vectors.biquad {
            let q = c.kind == "lowpass"
                ? Biquad.lowpass(cutoffHz: c.cutoffHz, fs: c.fs)
                : Biquad.highpass(cutoffHz: c.cutoffHz, fs: c.fs)
            let label = "\(c.kind) @ \(c.cutoffHz)Hz fs=\(c.fs)"
            XCTAssertEqual(q.b0, c.b0, accuracy: 1e-9, "\(label) b0")
            XCTAssertEqual(q.b1, c.b1, accuracy: 1e-9, "\(label) b1")
            XCTAssertEqual(q.b2, c.b2, accuracy: 1e-9, "\(label) b2")
            XCTAssertEqual(q.a1, c.a1, accuracy: 1e-9, "\(label) a1")
            XCTAssertEqual(q.a2, c.a2, accuracy: 1e-9, "\(label) a2")
        }
    }

    func testDetrendMatchesReference() {
        let c = Self.vectors.filtfilt
        let got = Filters.movingAverageDetrend(c.input, fs: c.fs)
        assertClose(got, c.detrended, tolerance: 1e-7, "movingAverageDetrend")
    }

    func testBandpassMatchesReference() {
        let c = Self.vectors.filtfilt
        let got = Filters.bandpass(c.input, fs: c.fs)
        assertClose(got, c.bandpassed, tolerance: 1e-7, "bandpass (zero-phase)")
    }

    func testAutocorrelationMatchesReference() {
        let c = Self.vectors.autocorrelation
        let got = Autocorrelation.compute(c.input)
        assertClose(got, c.acf, tolerance: 1e-9, "autocorrelation")
    }

    func testParabolicRefinement() {
        for c in Self.vectors.parabolic {
            let got = Autocorrelation.parabolicRefine(c.values, index: c.index)
            XCTAssertEqual(got, c.refined, accuracy: 1e-9, "parabolicRefine \(c.values)")
        }
    }

    func testRMSSDMatchesReference() {
        for c in Self.vectors.rmssd {
            let got = HRV.rmssd(peaks: c.peaks, fs: c.fs)
            if let expected = c.rmssdMs {
                XCTAssertNotNil(got, "expected RMSSD for \(c.peaks)")
                XCTAssertEqual(got ?? .nan, expected, accuracy: 1e-9, "rmssd \(c.peaks)")
            } else {
                XCTAssertNil(got, "expected nil RMSSD for \(c.peaks)")
            }
        }
    }

    // MARK: - End to end

    func testPipelineMatchesReference() {
        for c in Self.vectors.pipeline {
            let result = PPGAnalyzer.analyze(timestamps: c.timestamps, values: c.values)
            let e = c.expected

            XCTAssertEqual(result.sampleRate, e.fs, accuracy: 1e-9, "\(c.name) sample rate")

            if let expectedBPM = e.bpm {
                XCTAssertNotNil(result.bpm, "\(c.name): expected an estimate")
                XCTAssertEqual(result.bpm ?? .nan, expectedBPM, accuracy: 1e-6, "\(c.name) bpm")
            } else {
                XCTAssertNil(result.bpm, "\(c.name): expected no estimate")
            }
            XCTAssertEqual(result.confidence, e.confidence, accuracy: 1e-6, "\(c.name) confidence")
            XCTAssertEqual(result.isReportable, e.isReportable, "\(c.name) reportable")
            XCTAssertEqual(result.beatCount, e.beatCount, "\(c.name) beat count")

            if let expectedHRV = e.rmssdMs {
                XCTAssertEqual(result.rmssdMs ?? .nan, expectedHRV, accuracy: 1e-6, "\(c.name) rmssd")
            } else {
                XCTAssertNil(result.rmssdMs, "\(c.name) rmssd should be nil")
            }
        }
    }

    /// The accuracy claim the product rests on, restated as a test.
    func testPipelineRecoversTrueRateOnGoodSignals() {
        for c in Self.vectors.pipeline where c.expected.isReportable {
            let result = PPGAnalyzer.analyze(timestamps: c.timestamps, values: c.values)
            guard let bpm = result.bpm else {
                return XCTFail("\(c.name): no estimate for a reportable case")
            }
            XCTAssertLessThan(abs(bpm - c.trueBPM), 3.0,
                              "\(c.name): estimated \(bpm) for a true rate of \(c.trueBPM)")
        }
    }

    /// The safety property: a signal with no real pulse must never be reported.
    func testGarbageSignalIsRejected() {
        guard let garbage = Self.vectors.pipeline.first(where: { $0.name == "garbage_no_finger" }) else {
            return XCTFail("missing garbage_no_finger vector")
        }
        let result = PPGAnalyzer.analyze(timestamps: garbage.timestamps, values: garbage.values)
        XCTAssertFalse(result.isReportable,
                       "a signal with no pulse was reported as a heart rate of \(result.bpm ?? -1)")
        XCTAssertLessThan(result.confidence, PPGConstants.confidenceThreshold)
    }
}
